---

-   name: Install node.js and npm.
    apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
    with_items:
        - nodejs-legacy  # Not nodejs (without -legacy) package because it links node executable wrongly to nodejs.
        - npm

-   name: Install lessc via npm (globally)
    npm: name=less global=yes state=latest
