---


- name: Create the virtualenv
  command: virtualenv {{ virtualenv_path }} --no-site-packages
           creates={{ virtualenv_path }}/bin/activate

- name: Directory for logs
  file: path={{ virtualenv_path }}/logs
        state=directory

- name: Add to end of virtualenv activate file ENV DJANGO_SETTINGS_MODULE etc.
  lineinfile:
        dest={{ virtualenv_path }}/bin/activate
        line="export ENV={{ env }}; export DJANGO_SETTINGS_MODULE='{{ application_name }}.settings.{{ env }}';"
        insertafter=EOF

- name: Go to codebase path on activate of virtualenv
  lineinfile:
        dest={{ virtualenv_path }}/bin/activate
        line="cd {{ django_manage_py_path }}"
        insertafter=EOF

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ django_manage_py_path }}/requirements/{{ env }}.txt

- name: Activate the virtualenv everytime automatically
  lineinfile:
        dest={{ home_path }}/.bashrc
        line="source {{ virtualenv_path }}/bin/activate"
        insertafter=EOF

- name: Ensure that the virtualenv file permissions are set properly
  file: path={{ virtual_envs_home }}
        recurse=yes
        owner={{ app_code_user }}
        group={{ app_code_group }}
        state=directory
