---

# See https://coderwall.com/p/0nckqg
-   name: reboot server
    command: shutdown -r now 'Rebooting to complete system upgrade'
        removes=/var/run/reboot-required
    notify: wait for server reboot
    async: 0
    poll: 0
    ignore_errors: true

-   name: wait for server reboot
    sudo: false
    local_action:
        module: wait_for
            host={{ inventory_hostname }}
            port=22
            state=started
            delay=1
            timeout=120
