---

-   name: Install Nginx
    apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
    tags: packages
    with_items:
        - python-passlib  # For managing htpasswd files.
        - nginx

-   name: Create the Nginx configuration file
    template: src=nginx_conf.j2
            dest=/etc/nginx/sites-available/{{ application_name }}.conf
            backup=yes
    notify: reload nginx
    tags: htpasswd

-   name: Ensure that the default site is disabled
    file: path=/etc/nginx/sites-enabled/default
        state=absent
    notify: reload nginx

-   name: Create htpasswd for basic http auth
    htpasswd: path=/etc/nginx/htpasswd_{{ project_name }}
            name={{ project_name }}
            password={{ project_name }}-rules
            owner=root
            group=www-data
            mode=0640
    tags: htpasswd

-   name: Ensure that the application site is enabled
    file: src=/etc/nginx/sites-available/{{ application_name }}.conf
        dest=/etc/nginx/sites-enabled/{{ application_name }}.conf
        state=link
    notify: reload nginx

-   name: Ensure Nginx service is started
    service: name=nginx state=started enabled=yes
    tags: quick
