---

-   name: Install uwsgi
    apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
    with_items:
        - uwsgi
        - uwsgi-plugin-python
    notify:
        - restart uwsgi

-   name: Create the uwsgi configuration file
    template: src=uwsgi_ini.j2
            dest=/etc/uwsgi/apps-available/{{ application_name }}.ini
            backup=yes
    notify: restart uwsgi

-   name: Create the uwsgi params file
    template: src=params.j2
            dest={{ virtualenv_path }}/uwsgi_params
            backup=yes
    notify: restart uwsgi

-   name: Ensure that the application is enabled
    file: src=/etc/uwsgi/apps-available/{{ application_name }}.ini
        dest=/etc/uwsgi/apps-enabled/{{ application_name }}.ini
        state=link
    notify: restart uwsgi

-   name: Ensure uwsgi service is started
    service: name=uwsgi state=restarted enabled=yes
    tags: quick
    notify:
        - restart nginx
